apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: gdlns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gdlimbani/smartpps-backend:20241101
        ports:
        - containerPort: 80
